// Code generated by MockGen. DO NOT EDIT.
// Source: post_transfers.go
//
// Generated by this command:
//
//	mockgen -source=post_transfers.go -destination=service_mock.go -package=http
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	core "qonto/internal/core"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBulkTransferProcessor is a mock of BulkTransferProcessor interface.
type MockBulkTransferProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockBulkTransferProcessorMockRecorder
	isgomock struct{}
}

// MockBulkTransferProcessorMockRecorder is the mock recorder for MockBulkTransferProcessor.
type MockBulkTransferProcessorMockRecorder struct {
	mock *MockBulkTransferProcessor
}

// NewMockBulkTransferProcessor creates a new mock instance.
func NewMockBulkTransferProcessor(ctrl *gomock.Controller) *MockBulkTransferProcessor {
	mock := &MockBulkTransferProcessor{ctrl: ctrl}
	mock.recorder = &MockBulkTransferProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBulkTransferProcessor) EXPECT() *MockBulkTransferProcessorMockRecorder {
	return m.recorder
}

// ProcessBulkTransfer mocks base method.
func (m *MockBulkTransferProcessor) ProcessBulkTransfer(ctx context.Context, bulkTransfer core.BulkTransfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessBulkTransfer", ctx, bulkTransfer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessBulkTransfer indicates an expected call of ProcessBulkTransfer.
func (mr *MockBulkTransferProcessorMockRecorder) ProcessBulkTransfer(ctx, bulkTransfer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessBulkTransfer", reflect.TypeOf((*MockBulkTransferProcessor)(nil).ProcessBulkTransfer), ctx, bulkTransfer)
}
